### ISSUE TITLE
When will the code be available? 

### ISSUE THREAD

**Issue by Runsong123** [surfsplatting/surfsplatting.github.io#1]
Dear author,

Thanks for your exciting work.
I want to test your methods in my experiments and I want to know when the code will be available.
Looking forward to your reply. Many thanks in advance.

Bests,
Runsong

**Comment by surfsplatting** [comment]
Hi, thanks for you interest. 

This project is under evaluation and the code will be released upon approval. Hopefully, the code will be released in the next two weeks.

**Comment by Runsong123** [comment]
Got it. Thanks for your kind reply!
